# Generated by Django 4.0.3 on 2023-04-06 11:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('adminphoto', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='subservices',
            name='service',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='adminphoto.services'),
        ),
    ]
