# Generated by Django 4.0.3 on 2023-04-06 15:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminphoto', '0003_remove_subservicesimages_subservice_services_after_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Portfolio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('src', models.ImageField(blank=True, default='image-placeholder-500x500.jpg', null=True, upload_to='')),
                ('thumb', models.ImageField(blank=True, default='image-placeholder-500x500.jpg', null=True, upload_to='')),
            ],
        ),
    ]
