# Generated by Django 4.0.3 on 2023-04-06 15:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminphoto', '0004_portfolio'),
    ]

    operations = [
        migrations.AddField(
            model_name='portfolio',
            name='date_created',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
