# Generated by Django 4.0.3 on 2023-04-07 13:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminphoto', '0010_alter_contact_address_alter_contact_caption_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subservices',
            name='after',
            field=models.FileField(blank=True, default='image-placeholder-500x500.jpg', null=True, upload_to=''),
        ),
    ]
