# Generated by Django 4.0.3 on 2023-04-08 09:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminphoto', '0014_slide'),
    ]

    operations = [
        migrations.CreateModel(
            name='SlideInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('caption', models.CharField(max_length=200)),
                ('cover', models.ImageField(blank=True, default='image-placeholder-500x500.jpg', null=True, upload_to='')),
            ],
        ),
    ]
