# Generated by Django 4.0.3 on 2023-04-08 09:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminphoto', '0015_slideinfo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='services',
            name='before',
        ),
        migrations.AddField(
            model_name='services',
            name='button_name',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
