# Generated by Django 4.0.3 on 2023-04-08 09:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminphoto', '0016_remove_services_before_services_button_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='contact',
            name='short_info',
            field=models.TextField(blank=True),
        ),
    ]
